# Generated by Django 2.2.4 on 2019-08-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('space', models.CharField(max_length=20)),
                ('guest', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=50)),
                ('img1', models.FileField(default='', upload_to='room/img1')),
                ('img2', models.FileField(default='', upload_to='room/img2')),
                ('img3', models.FileField(default='', upload_to='room/img3')),
                ('img4', models.FileField(default='', upload_to='room/img4')),
                ('img5', models.FileField(default='', upload_to='room/img5')),
                ('img6', models.FileField(default='', upload_to='room/img6')),
            ],
        ),
    ]
