# Generated by Django 2.2.4 on 2019-09-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punjabi', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='nm',
            new_name='user_nm',
        ),
    ]
