# Generated by Django 2.2.4 on 2019-09-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punjabi', '0004_auto_20190903_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roombook',
            new_name='Booking',
        ),
    ]
