# Generated by Django 2.2.4 on 2019-09-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punjabi', '0005_auto_20190903_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50)),
                ('startdate', models.CharField(max_length=50)),
                ('enddate', models.CharField(max_length=50)),
            ],
        ),
    ]
