# Generated by Django 2.2.4 on 2019-09-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punjabi', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='room_id',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
