# Generated by Django 2.2.4 on 2019-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punjabi', '0008_auto_20190907_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=100)),
                ('img', models.FileField(default='', upload_to='gallery')),
            ],
        ),
    ]
