# Generated by Django 2.2.4 on 2019-09-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punjabi', '0009_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=100)),
                ('cat', models.CharField(max_length=100)),
            ],
        ),
    ]
