# Generated by Django 2.2.4 on 2019-09-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punjabi', '0010_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=50)),
                ('em', models.CharField(max_length=50)),
                ('no', models.CharField(max_length=15)),
                ('sub', models.CharField(max_length=150)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
    ]
